### DISCUSSION TITLE
LDAP inside Docker

### DISCUSSION THREAD

**Discussion by MrDiba** [Leantime/leantime#1023] [Q&A] [answered]
I know there is a different LDAP topic open at this moment, but as that one is more focused on AD I'm opening this new one.

I'm trying to get LDAP authentication working using the Docker container but I'm not getting anywhere.

The docker-compose configuration is as follow:
```
~# cat docker-compose.yml 
version: '3.3'

services:
  leantime_db:
    image: mysql:8.0
    container_name: mysql_leantime
    networks:
      - db
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: '321.qwerty'
      MYSQL_DATABASE: 'leantime'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '321.qwerty'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    networks:
      - proxy
      - db
    environment:
      # LEAN_APP_URL: 'https://domain.com/leantime'                     # Only needed for subdirectory setup; protocol (http or https) and base URL , trailing slash not needed
      LEAN_SITENAME: 'Leantime'                                         # Name of your site, can be changed later
      LEAN_DB_HOST: 'mysql_leantime'                                    # Database host, derived from container_name in leantime_db container
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: '321.qwerty'
      LEAN_DB_DATABASE: 'leantime'
      LEAN_DEFAULT_TIMEZONE: 'Europe/Amsterdam'                         # Set default server timezone
      LEAN_SESSION_PASSWORD: 'password'         # Salting sessions. Replace with a strong password
      LEAN_SESSION_EXPIRATION: 28800                                    # How many seconds after inactivity should we logout? 28800seconds = 8hours
      LEAN_DEBUG: "true"
      LEAN_LDAP_USE_LDAP: "true"
      LEAN_LDAP_HOST: "ldap.example.com"
      LEAN_LDAP_BASE_DN: "dc=example,dc=local"
      LEAN_LDAP_DN: "ou=Users,dc=example,dc=local"
      LEAN_LDAP_USER_DOMAIN: "@example.com"
    extra_hosts:
      - ldap.example.com:192.168.1.2

    volumes:
      - public_userfiles:/var/www/html/public/userfiles
      - userfiles:/var/www/html/userfiles
#    ports:
#      - "8080:80"                                                       # The port to expose and access Leantime
    depends_on:
      - leantime_db                                                     # Don't start Leantime unles leantime_db is running

volumes:
  db_data:
  userfiles:
  public_userfiles:

networks:
  proxy:
    external: true
  db:
```
The proxy network is there for a reverse proxy, but this is out of scope as I can login using a local user without a problem.

I tried to enable debugging to get some more information using `LEAN_DEBUG: "true"` but I can't get any more information. I do not know where the debug information should show? The container logs are only showing:
```
leantime       | 127.0.0.1 -  12/Oct/2022:12:23:59 +0000 "GET /index.php" 200
leantime       | 127.0.0.1 -  12/Oct/2022:12:23:59 +0000 "PATCH /index.php" 200
leantime       | 127.0.0.1 -  12/Oct/2022:12:25:16 +0000 "POST /index.php" 303
leantime       | 127.0.0.1 -  12/Oct/2022:12:25:16 +0000 "GET /index.php" 200
leantime       | 127.0.0.1 -  12/Oct/2022:12:25:16 +0000 "GET /index.php" 200
leantime       | 127.0.0.1 -  12/Oct/2022:12:25:16 +0000 "PATCH /index.php" 303
leantime       | 127.0.0.1 -  12/Oct/2022:12:25:16 +0000 "GET /index.php" 200
```
The docker host can connect to the LDAP server so I assume this is not the problem.

**Comment by marcelfolaron** [comment]
Hi,

Logs for Leantime can be found in the container under
resources/logs/error.log

Now taking a look at your config. Not sure if this is a typo but if you
host is ldap.example.com the baseDN should be dc=ldap,dc=example,dc=com

Same in the user ldapDN: ou=Users,dc=ldap,dc=…

Do the ldapKeys align with your ldap directory structure?
https://docs.leantime.io/#/installation/configuration?id=ldap-configuration-beta

**Reply by MrDiba** [reply]
Unfortunately the error.log is empty.  

The baseDN is actually not a typo, our ldap server is configured to have `ldap.example.com` as hostname but `dc=example,dc=local` as baseDN. (Not my choice but something legacy ;) )

Taking the defaults from https://github.com/Leantime/leantime/blob/master/config/configuration.sample.php : 
```
    public $ldapKeys = '{ 
        "username":"uid",
        "groups":"memberof",
        "email":"mail",
        "firstname":"displayname",
        "lastname":"",
        "phonenumber":""
        }';
```
And cross referencing to my ldap server I see that there are some fields missing in my LDAP server. I do not have a `memberof` and `mail` field for some users.

I assume that `memberof` is not required if I would not use the "auto group" feature. But as you login with the e-mail address I can assume that the `mail` field is something that is required? Or is the login created with the `uid` in combination with the `user_domain`?

**Comment by MrDiba** [comment, marked as answer]
I have updated to v2.2.8 and that fixed the issue for some reason. I saw that the previous version (v2.2.7) did not communicated with the LDAP server all when checking the LDAP logs.

For future references here the updated (And working) environment variables.
```
environment:
  # LEAN_APP_URL: 'https://domain.com/leantime'                     # Only needed for subdirectory setup; protocol (http or https) and base URL , trailing slash not needed
  LEAN_SITENAME: 'Leantime'                                         # Name of your site, can be changed later
  LEAN_DB_HOST: 'mysql_leantime'                                    # Database host, derived from container_name in leantime_db container
  LEAN_DB_USER: 'admin'
  LEAN_DB_PASSWORD: '321.qwerty'
  LEAN_DB_DATABASE: 'leantime'
  LEAN_DEFAULT_TIMEZONE: 'Europe/Amsterdam'                         # Set default server timezone
  LEAN_SESSION_PASSWORD: 'password'         # Salting sessions. Replace with a strong password
  LEAN_SESSION_EXPIRATION: 28800                                    # How many seconds after inactivity should we logout?  28800seconds = 8hours
  LEAN_DEBUG: "true"
  LEAN_LDAP_USE_LDAP: "true"
  LEAN_LDAP_HOST: "192.168.1.2"
  LEAN_LDAP_BASE_DN: "dc=example,dc=local"
  LEAN_LDAP_DN: "ou=Users,dc=example,dc=local"
  LEAN_LDAP_USER_DOMAIN: "@example.com"
  LEAN_LDAP_KEYS: '{"username":"uid","groups":"","email":"mail","firstname":"givenname","lastname":"sn"}'
```
I do notice that a regular database user logs in using `user@example.com` whilst an LDAP user just logs in with there username.
