### ISSUE TITLE
[BUG] Font Exo on login page not loaded

### ISSUE THREAD

**Issue by diderich** [Leantime/leantime#1086]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**
On the login screen, the `Exo`  font is used to display the welcome message, but the font is never loaded (and no alternatives, like Helvetica or Arial are specified). If the user does not have the font installed locally, the browser reverts to the default font.

```css
.row .regLeft .mainWelcome {
    font-family:Exo;
    font-size: 54px;
    padding-left:15px;
    font-weight:400;
}
```

**Expected behavior**
The font is loaded.

**Leantime Version**
2.2.10
