### ISSUE TITLE
[FEATURE] Provided Docker-Compose for Raspberry Pi (4)

### ISSUE THREAD

**Issue by samuscodes** [Leantime/leantime#1316]
This is less of a feature request and more a better way for an already existing but convoluted feature.

While there is an explanation on how to get Leantime running on a Raspberry Pi, I found that you just have to replace the database-image (alpine-mariadb instead of mysql) in the docker-compose and it runs perfectly.

I got it to work on my Raspberry Pi 4 (8GB RAM), hope this also works on other models:

```yaml
# BUILD ON RASPBERRY PI 4
version: '3'

services:

  leantime:
    container_name: 'leantime'
    image: 'leantime/leantime:latest'
    restart: 'unless-stopped'
    environment:
      LEAN_SITENAME: 'Leantime'  # Name of your site, can be changed later
      LEAN_SESSION_EXPIRATION: 28800  # How many seconds after inactivity should we logout?  28800seconds = 8hours
      LEAN_DB_HOST: 'leantime_mariadb'  # Database host, derived from container_name in leantime_db container
      LEAN_DB_DATABASE: 'db'
      LEAN_DB_USER: 'user'
      LEAN_DB_PASSWORD: 'password'
    volumes:
      - '</path/to>/Leantime/public_userfiles:/var/www/html/public/userfiles'
      - '</path/to>/Leantime/userfiles:/var/www/html/userfiles'
    ports:
      - "8080:80"
    depends_on:
      - 'mariadb'

  mariadb:
    container_name: 'leantime_mariadb'
    image: 'yobasystems/alpine-mariadb:latest'
    volumes:
      - '</path/to>/Leantime/mariadb:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    restart: 'unless-stopped'
    command: '--character-set-server=utf8 --collation-server=utf8_unicode_ci'
```
