### ISSUE TITLE
[BUG] 502 error for leantime.my.domain/dashboard/home when running the docker container

### ISSUE THREAD

**Issue by Aephir** [Leantime/leantime#1793]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted (Docker)

**Describe the bug**
I get to the login page if I navigate to `leantime.my.domain`, but after logging in, I get forwarded to leantime.my.domain/dashboard/home which shows the error `502 Bad Gateway`. If I manually re-enter `leantime.my.domain`, I get the the dashbaord and can use leantime, but since I'm trying to build an app with [nativefier](https://github.com/nativefier/nativefier), this won't work anymore.

I can't remember when this behavior started (a while ago, but it has worked fine for months before that) since I just manually navigated back to `leantime.my.domain` instead of trying to fix.

I tried setting `VIRTUAL_PORT: 80` as per [this comment](https://github.com/Leantime/leantime/issues/273#issuecomment-636493319).

The solution in #1341 is less useful in docker (since any pull of image would "undo").

**To Reproduce**
1. Set up leantime and db i docker-compose file (see config below)
2. Set up nginx as reverse proxy (I am assuming this isn't the issue, as this part used to work fine).
3. 'docker-compose up -d`
4. navigate to fwdn and log in.
5. See error 502 when directed to fqdn/dashboard/home

<details>

<summary> leantime and db config in docker-compose.yaml </summary>

```
  leantime_db:
    image: mysql:8.0
    container_name: leantime_mysql
    volumes:
      - /mnt/data/docker/leantime/leantime_db:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'RECACTED'
      MYSQL_DATABASE: 'leantime'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'RECACTED'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    environment:
      # LEAN_APP_URL: 'https://leantime.my.domain'                     # Only needed for subdirectory setup; protocol (http or https) and base URL , trailing slash not needed
      LEAN_SITENAME: 'Leantime'                                         # Name of your site, can be changed later
      LEAN_DB_HOST: 'leantime_mysql'                                    # Database host, derived from container_name in leantime_db container
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: 'RECACTED'
      LEAN_DB_DATABASE: 'leantime'
      LEAN_DEFAULT_TIMEZONE: 'Europe/Stockholm'                         # Set default server timezone
      LEAN_SESSION_PASSWORD: 'RECACTED'         # Salting sessions. Replace with a strong password
      LEAN_SESSION_EXPIRATION: 28800                                    # How many seconds after inactivity should we logout?  28800seconds = 8hours
    volumes:
      - /mnt/data/docker/leantime/public_userfiles:/var/www/html/public/userfiles
      - /mnt/data/docker/leantime/userfiles:/var/www/html/userfiles
    ports:
      - "10.0.30.21:8004:80"                                                       # The port to expose and access Leantime
    depends_on:
      - leantime_db                                                     # Don't start Leantime unless leantime_db is running
```

</details>

<details>

<summary> leantime-specific nginix conf (rest is standard and unchanged from linuxerver swag container) </summary>

```
server {
        listen 443 ssl;
        # listen 80;

        root /config/www;
        index index.html index.htm index.php;

        server_name leantime.my.domain

        include /config/nginx/ssl.conf;

        client_max_body_size 0;

        location / {
        #               auth_basic "Restricted";
        #               auth_basic_user_file /config/nginx/.htpasswd;
                        include /config/nginx/proxy.conf;
                proxy_pass http://10.0.30.21:8004;
        }
}
```
</details>

I haven't changed anything in either `docker-compose.yaml` or nginx's `leantime.conf` since initial setup, the only thing I have done is pull new images every now and then.

**Expected behavior**
Not getting a 502 error (like things were a few months ago).

**Leantime Version**
Not sure where to see (can't `docker exec -it leantime sh` and use `leantime --version`), but I did a pull of the leantime/leantime:latest today (August 3rd, 2023).

**Server**
nginx

**PHP / MySQL Version**
PHP v8.1.21 (what's in the docker image)
Mysql v8.0.34
