### ISSUE TITLE
[BUG] Could not send Emails via Leantime

### ISSUE THREAD

**Issue by pleibling** [Leantime/leantime#1840]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
If i create a leantime Container with docker-compose.yml - the SMTP Part in Environment doesn't work. - i try this:

```
version: '3.3'

services:
  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: always
    networks:
      - webapps
    environment:
      - LEAN_DB_HOST=mariadb
      - LEAN_DB_DATABASE=leantime
      - LEAN_DB_USER=leantime
      - LEAN_DB_PASSWORD=mypersonalpassword
      - LEAN_EMAIL_USE_SMTP=TRUE
      - LEAN_EMAIL_RETURN=info@domain.de
      - LEAN_EMAIL_SMTP_HOSTS=smtp.office365.com
      - LEAN_EMAIL_SMTP_USERNAME=info@domain.de
      - LEAN_EMAIL_SMTP_PASSWORD=mypersonalpassword
      - LEAN_EMAIL_SMTP_AUTO_TLS=TRUE
      - LEAN_EMAIL_SMTP_SECURE=true
      - LEAN_EMAIL_SMTP_PORT=25
    volumes:
      - /docker-data/leantime/public-data:/var/www/html/public/userfiles        # Volume to store public files, logo etc
      - /docker-data/leantime/user-data:/var/www/html/userfiles                 # Volume to store private user uploaded files
    ports:
      - 8082:80                                                                 # The port to expose and access Leantime
networks:
  webapps:
    external: true
    name: webapps
```

I get this error - it seems that the SMTP configuration are not use: sendmail: can't connect to remote host (127.0.0.1): Connection refused

Inside the container (docker exec -it leantime sh) i can connect to Office 365 (nc smtp.office365.com 25), i get the SMTP Banner from Office 365 and i see the connection in my Firewalllogs, But when i try to send to reset the Password via Email, it show "Password send", but i get no Mail (check Junkmail goo) and i see no connection on the Firewall.

**To Reproduce**
Check with Passwortreset via Email

**Expected behavior**
Normaly i expect, that leantime connect to Office 365 except 127.0.0.1

**Leantime Version**
Which Leantime version are you using

**Server**
Docker

**PHP / MySQL Version**
Docker, MariaDB

**Additional context**
