### ISSUE TITLE
[BUG] Milestones Section Missing

### ISSUE THREAD

**Issue by Jono-Moss** [Leantime/leantime#2081]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
When using the docker image (latest) tag, when logging on, the Milestone section is gone.
This happens with a new clean installation as well as with updating from a previous version. 

**To Reproduce**
1. Create a new instance of Leantime in docker. In my case docker compose.
```
version: '3.3'

services:
  leantime_db:
    image: mysql:8.0
    container_name: mysql_leantime
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'asd'
      MYSQL_DATABASE: 'leantime'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'asd'
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

  leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    environment:                    
      LEAN_SITENAME: 'Leantime'                                         
      LEAN_DB_HOST: 'mysql_leantime'                                    
      LEAN_DB_USER: 'admin'
      LEAN_DB_PASSWORD: 'asd'
      LEAN_DB_DATABASE: 'leantime'
      LEAN_DEFAULT_TIMEZONE: 'Africa/Johannesburg'                         
      LEAN_SESSION_PASSWORD: 'asdasdadasdasdasdasdasd'         
      LEAN_SESSION_EXPIRATION: 28800                                    
      PUID: 1000
      PGID: 1000
    volumes:
      - ./public_userfiles:/var/www/html/public/userfiles
      - ./userfiles:/var/www/html/userfiles
    ports:
      - "83:80"                                                       
    depends_on:
      - leantime_db                                                    

```
3. open Leantime and and go through the "Setup wizard".
4. you will see that the milestone section in not in the left bar menu and there is no other way to access it. see below image.

<img width="1674" alt="Screenshot 2023-11-13 at 11 15 20" src="https://github.com/Leantime/leantime/assets/118931687/5babca4b-bb3d-4803-8e39-9b3fda25b562">

**Expected behavior**
There should be a menu option to go to the Milestones section.

**Leantime Version**
2.4.7 - docker image tag latest

**Server**
Apache

**PHP / MySQL Version**
8.1.25/8.0
