### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dartinger** [Leantime/leantime#2120]
**What set up are you using**
* [ ] Cloud Hosted Version
* [x] Self Hosted

**Describe the bug**
If I add a Milestone to a goal and Save it, the milestone appears inside the goal. 
But as soon as I save the goal, it isn't linked anymore with the goal. 

**To Reproduce**
1. Go to 'Goals' > Add a new Goal (In my case "Website Relaunch")
2. Link a milestone to the goal (In my case also "Website Relaunch" as Milestone)
3. 'Save' the linked milestone
4. 'Save & Close' the Goal

However, this error does not always occur. I also don't understand exactly when this error happens, as it looks very random. 
As I understand it, the goal is linked to the milestone in the "milestoneId" column in the "zp_canvas_items" table.
This field is empty if the error occurs. 

I also checked what happens when I open a goal and simply save it. 
If a milestone has been linked properly, it can still happen that the milestone disappears afterwards. 

**Expected behavior**
The milestone should be linked, until I 'Remove' it with a click on the button inside the goal. 

**Leantime Version**
Leantime v2.4.7

**Server**
Stack: 
- Debian 11 (bullseye)
	- Portainer:2.18.3
		- MySQL:8.0
		- Leantime:latest (2.4.7)

**PHP / MySQL Version**
MySQL v8.0

**Additional context**

docker-stack.yml
```
version: '3.3'

services:
  leantime_db:
    image: mysql:8.0
    container_name: tickets_mysql
    volumes:
      - /home/www/leantime/mysql:/var/lib/mysql
    restart: unless-stopped
    env_file: stack.env
    networks:
      - proxy
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci


  leantime:
    image: leantime/leantime:latest
    container_name: tickets_leantime
    restart: unless-stopped
    env_file: stack.env
    labels:
      - traefik.enable=true
      - traefik.leantime.network=proxy
      - traefik.http.routers.leantime.entrypoints=websecure
      - traefik.http.routers.leantime.rule=Host(`tickets.example.de`)
    networks:
      - proxy
    volumes:
      - /home/www/leantime/public:/var/www/html/public/userfiles
      - /home/www/leantime/userfiles:/var/www/html/userfiles
    ports:
      - "${LEAN_PORT}:80"
    depends_on:
      - leantime_db

volumes:
  db_data:
  userfiles:
  public_userfiles:

networks:
  proxy:
    external: true
```

stack.env:
```
LEAN_APP_URL=https://tickets.example.de
LEAN_APP_DIR=
LEAN_PORT=8081
LEAN_DEBUG=0
MYSQL_ROOT_PASSWORD=changeme123
MYSQL_DATABASE=leantime
MYSQL_USER=lean
MYSQL_PASSWORD=changeme123
LEAN_DB_HOST=leantime_db
LEAN_DB_USER=lean
LEAN_DB_PASSWORD=changeme123
LEAN_DB_DATABASE=leantime
LEAN_DB_PORT=3306
LEAN_SITENAME=Leantime
LEAN_LANGUAGE=en-US
LEAN_DEFAULT_TIMEZONE=Europe/Berlin
LEAN_ENABLE_MENU_TYPE=false
LEAN_SESSION_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
LEAN_SESSION_EXPIRATION=28800
LEAN_LOG_PATH=null
LEAN_LOGO_PATH=/images/logo.svg
LEAN_PRINT_LOGO_URL=/images/logo.jpg
LEAN_DEFAULT_THEME=default
LEAN_PRIMARY_COLOR=#1b75bb
LEAN_SECONDARY_COLOR=#81B1A8
LEAN_KEEP_THEME=true
LEAN_USER_FILE_PATH=userfiles/
LEAN_DB_BACKUP_PATH=backupdb/
LEAN_EMAIL_RETURN=
LEAN_EMAIL_USE_SMTP=false
LEAN_EMAIL_SMTP_HOSTS=
LEAN_EMAIL_SMTP_AUTH=true
LEAN_EMAIL_SMTP_USERNAME=
LEAN_EMAIL_SMTP_PASSWORD=
LEAN_EMAIL_SMTP_AUTO_TLS=true
LEAN_EMAIL_SMTP_SECURE=
LEAN_EMAIL_SMTP_SSLNOVERIFY=false
LEAN_EMAIL_SMTP_PORT=
```
