### ISSUE TITLE
Leantime via docker compose refuses to install

### ISSUE THREAD

**Issue by glenjolley** [Leantime/leantime#2997]
### What is your set up?

Self Hosted Docker

### Version

:latest

### Describe the issue

On a fresh install via docker compose (handled by dockge), any attempt to install leantime via the /install page simply reloads back to install page and doesn't proceed to make any changes.

No errors are recorded in the log file or displayed on screen.

Tried both with and without declaring PUID/GUID in case this was a permissions error, but there's no difference. Have also tried with and without using nginx proxy manager for a friendly url (leantime.lan vs 192.168.0.2), both to no avail.

Also worth noting that if I attempt to persist the non-mysql volumes into a custom location, the terminal on dockge reports that leantime cannot find the database (whether this is persisted in a custom location or just the default location provided in the compose file) - simply persisting the leantime container folders seems enough to break the link with the sql container.

For reference, here is my compose:

```
version: "3.3"
services:
  leantime_db:
    image: mysql:8.4
    container_name: mysql_leantime
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: ./.env # Environment file with settings
    networks:
      - leantime-net
    command: --character-set-server=UTF8MB4 --collation-server=UTF8MB4_unicode_ci
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 30s
      timeout: 10s
      retries: 3
  leantime:
    image: leantime/leantime:${LEAN_VERSION:-latest}
    restart: unless-stopped
    env_file: ./.env # Environment file with settings
    # Add security options
    security_opt:
      - no-new-privileges:true
    # Add capabilities
    cap_add:
      # - CAP_NET_BIND_SERVICE
      - CAP_CHOWN
      - CAP_SETGID
      - CAP_SETUID
    ports:
      - ${LEAN_PORT:-8080}:8080
    networks:
      - leantime-net
      - webapps_internal
    volumes:
      - public_userfiles:/var/www/html/public/userfiles # Volume to store public files, logo etc
      - userfiles:/var/www/html/userfiles # Original volume name for compatibility
      - plugins:/var/www/html/app/Plugins # Plugin storage
      - logs:/var/www/html/storage/logs # Log storage
    depends_on:
      leantime_db:
        condition: service_healthy
  # Add a helper container for volume permissions
  # Run via docker compose --profile mysql_helper up -d
  mysql_helper:
    image: mysql:8.4
    command: chown -R mysql:mysql /var/lib/mysql
    volumes:
      - db_data:/var/lib/mysql
    user: root
    profiles:
      - helper
volumes:
  db_data: null
  userfiles: null # New volume for public files
  public_userfiles: null
  plugins: null
  logs: null
networks:
  leantime-net: null
  webapps_internal:
    external: true
```

And my corresponding .env file, declared via dockge:

```
# This is a sample configuration file with all possible configuration options.
# If you don't want to maintain a file like this you can pass in all variables via Server Variables

LEAN_PORT = '8080'                                 # The port to expose and access Leantime
LEAN_APP_URL = 'http://leantime.lan'                                  # Base URL, needed for subfolder or proxy installs (including http:// or https://)

LEAN_DEBUG = 0                                     # Debug flag

# Database - MySQL container
MYSQL_ROOT_PASSWORD = 'wiK5ENMbVmA3cj'                # MySQL root password
MYSQL_DATABASE = 'leantime'                        # Database name
MYSQL_USER = 'lean'                                # Database username
MYSQL_PASSWORD = '7HWjJtSgSUG6Ny'                     # Database password

# Database - leantime container
LEAN_DB_HOST = 'mysql_leantime'                    # Database host
LEAN_DB_USER = 'lean'                              # Database username (needs to be the same as MYSQL_USER)
LEAN_DB_PASSWORD = '7HWjJtSgSUG6Ny'                   # Database password (needs to be the same as MYSQL_PASSWORD)
LEAN_DB_DATABASE = 'leantime'                      # Database name (needs to be the same as MYSQL_DATABASE)
LEAN_DB_PORT = '3306'                              # Database port
```

### Reproduction steps

1.
2.
3.
...

### Error Logs (LEANTIMEFOLDER/storage/logs)

No logs are being generated, nor are there any console errors.
