### ISSUE TITLE
[BUG] Running behind a Caddy reverse proxy that provides TLS causes the popups to break

### ISSUE THREAD

**Issue by toby-griffiths** [Leantime/leantime#479]
*If you have problems with the installation please use our [community forum](https://community.leantime.io)*

**Describe the bug**

I use the [Caddy reverse proxy](https://github.com/lucaslorentz/caddy-docker-proxy) to provide automatic TSL secured connections.  When I browse the site for the first time I see a load of "An error occured" popups, which are cause by the fact that some requests are being made over http, rather than https, and so the browser is bloking them.

![image](https://user-images.githubusercontent.com/4817007/136547016-8ead0e64-f74e-49bf-bdbc-9179de853091.png)

Here are the browser console errors…
![image](https://user-images.githubusercontent.com/4817007/136547124-65b4350d-f2a2-4566-bd3a-a86e9d19da07.png)

**To Reproduce**
1. Setup a caddy docker proxy (I have a setup script for this [on Github](https://raw.githubusercontent.com/toby-griffiths/caddy-docker-proxy/main/setup))
2. Update the `docker-compose.yml` file to add the caddy proxy labels, and add the web service to the caddy network…
   ```
   version: '3.3'
   
   services:
      db:
        image: mysql:5.7
        container_name: mysql_leantime
        volumes:
          - db_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '321.qwerty'
            MYSQL_DATABASE: 'leantime'
            MYSQL_USER: 'admin'
            MYSQL_PASSWORD: '321.qwerty'
        ports:
          - "3306:3306"
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
      web:
        image: leantime/leantime:latest
        container_name: leantime
        environment:
            LEAN_DB_HOST: 'mysql_leantime'
            LEAN_DB_USER: 'admin'
            LEAN_DB_PASSWORD: '321.qwerty'
            LEAN_DB_DATABASE: 'leantime'
        labels:
          caddy: leantime.localhost                # <== Add this label
          caddy.reverse_proxy: '{{upstreams 80}}' # <== Add this label
        networks:
          default: # <== Add this network here
          caddy:   # <== Add this network here
        ports:
          - "9000:9000"
        depends_on:
          - db
   volumes:
       db_data: {}
   
   networks:            # <== Add this section as follows
     default:
     caddy:
       external: true
   ```
3. Run `docker-compose up -d`
4. Access the site via `https://leantime.localhost`
5. See errors as you navigate around

**Expected behavior**
Popups should appear as they do when viewing over an insecure connection

**Leantime Version**
Which Leantime version are you using

**Server**
Apache (using your docker compose setup)

**PHP / MySQL Version**
PHP: 7.2.34 (as per your docker-compose file)
MySQL: 5.7 (as per your docker-compose file)

**Additional context**
If the links to these URLs were updated to remove the protocol, then the current protocol would be used, so amending `http://leantime.localhost/…` to `//leantime.localhost/…`, as explainer [here](https://www.paulirish.com/2010/the-protocol-relative-url/), then this should solve the issue.

I've not had time to dig around the code to see where this is, but I could probably submit a PR in the future for this, but can't promise when.
