### ISSUE TITLE
Volumes needed for leantime

### ISSUE THREAD

**Issue by dekiesel** [Leantime/leantime#775]
Hi,

thank you for this amazing piece of software!

I found a small issue with the docker-compose files: Images (profile pics also) aren't persisted. If I upload a profile pic (or any picture) everything works well, but if I recreate the container it disappears.

I saw [here](https://github.com/Leantime/docker-leantime/commit/9ed1612c4f2bb3a90d857dc5e9696bc03a1ec25d) that volumes have been removed, but I think at the very least `userfiles` should be there.

I have added a few volumes to my `docker-compose.yaml` and it works as expected now. Only draw back with my setup is that I need to change the owner of the folder on the host to `www-data` for it to work.

```
version: '3.3'

services:
   db:
     image: beercan1989/arm-mysql:5.7
     container_name: mysql_leantime
     volumes:
       - ${DBDATA}:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: 'leantime'
         MYSQL_USER: 'admin'
         MYSQL_PASSWORD: '321.qwerty'
         #ports:
     #  - "3306:3306"
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
   web:
     image: leantime:2.1.7
     container_name: leantime
     environment:
         LEAN_DB_HOST: 'mysql_leantime'
         LEAN_DB_USER: 'admin'
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: 'leantime'
     volumes:
       #- $LEAN_CONFIG:/var/www/html/config
       - ${LEAN_PUB_USERFILES}:/var/www/html/public/userfiles
       - ${LEAN_USERFILES}:/var/www/html/userfiles
       - ${LEAN_LOGS}:/var/www/html/resources/logs
     ports:
     #  - "9000:9000"
       - "100:80"
     depends_on:
       - db
networks:
  default:
    external:
      name: leantime-net
```

May I ask what the reason was to remove the volumes?
