### ISSUE TITLE
Gateway timeout when creating new projects when deployed with portainer

### ISSUE THREAD

**Issue by damntourists** [Leantime/leantime#777]
Hi there,

For the most part, everything seems to be working as expected, however, any time I try to create a new project, I get the following error:

```
Gateway Timeout

The gateway did not receive a timely response from the upstream server or application.
Apache/2.4.43 (Unix) Server at projects.bronson.sh Port 80
```

I'm using Portainer to deploy. I've tried the following stack configuration with swarm enabled:
```
version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: '321.qwerty'
         MYSQL_DATABASE: leantime
         MYSQL_USER: admin
         MYSQL_PASSWORD: '321.qwerty'
     ports:
       - "3306:3306"
     command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
   web:
     image: leantime/leantime:latest
     environment:
         LEAN_DB_HOST: db
         LEAN_DB_USER: admin
         LEAN_DB_PASSWORD: '321.qwerty'
         LEAN_DB_DATABASE: leantime
         LEAN_APP_URL: https://projects.bronson.sh
     ports:
       - "6900:9000"
       - "6080:80"
     depends_on:
       - db
     volumes:
       - /home/brett/portainer_volumes/leantime/configuration.php:/var/www/html/config/configuration.php # SMTP config

volumes:
    db_data: {}
```

It's strange because there aren't any errors thrown in either container when this occurs. No javascript errors, no container errors, just suddenly unable to POST to the `/projects/newProject` endpoint. When this happens the web container never recovers and I have to re-create the container for it to work again.

I've tried the following with the same result:
* Accessing directly by IP:Port (with an updated lean_app_url) which worked but couldn't create new projects
* Creating an `overlay` network within the stack configuration instead of as step one by command line before deployment which worked but couldn't create new projects
* Creating a `leantime-net` network like the docs mention for the first step. Same result.
