### ISSUE TITLE
php-fpm 'httpd entered FATAL state, too many start retries too quickly'

### ISSUE THREAD

**Issue by 0x0256c03a** [Leantime/leantime#908]
Hi ! I do have an issue using leantime + docker. I am using the offical docker-compose file just a little tweaked.
The configuration seems to work and the container continues to run however nothing seems to run and by looking at the logs I see that fpm seems in a hurry....

![image](https://user-images.githubusercontent.com/106661682/186172020-b3395f7c-6cb1-49a7-ab67-43cc51ea0545.png)

```yml

leantime:
    image: leantime/leantime:latest
    container_name: leantime
    restart: unless-stopped
    volumes:
      - /docker/leantime/public_userfiles:/var/www/html/public/userfiles
      - /docker/leantime/userfiles:/var/www/html/userfiles

```
The environment configuration is in a .env file.

I've seen the same issue before but don't seems to work:
https://stackoverflow.com/questions/56889046/supervisor-celery-entered-fatal-state-too-many-start-retries-too-quickly

Any help if someone encountered the same problem ?
